version: '3.7'
services:
    web:
        image: nginx:latest
        ports:
            - "8082:8082"
            - "8083:8083"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:delegated
            - ./nginx_xhprof.conf:/etc/nginx/conf.d/xhprof.conf
            - ./app:/app:delegated
            - xhprof:/var/xhprof/xhprof-2.3.10
        restart: always
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app:delegated
            - xhprof:/var/xhprof/xhprof-2.3.10
            - ./moodle-browser-config:/app/moodle-browser-config
        restart: always
    cron:
        build:
            context: .
            dockerfile: CRON.Dockerfile
        restart: always
        volumes:
            - ./app:/app:delegated
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'purple'
            MYSQL_USER: 'moodleuser'
            MYSQL_PASSWORD: 'moodlepass'
            MYSQL_DATABASE: 'moodle44'
        restart: always
        volumes:
            - mysqldata:/var/lib/mysql:delegated
        ports:
            - 3308:3306
    redis:
        image: redis:latest
        command: redis-server --save "" --appendonly no
        restart: always

    firefox:
        image: selenium/node-firefox:4.28.1-20250202
        shm_size: 2gb
        depends_on:
        - selenium-hub
        environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        ports:
        - "6902:5900"

    selenium-hub:
        image: selenium/hub:4.28.1-20250202
        ports:
        - "4442:4442"
        - "4443:4443"
        - "4444:4444"

volumes:
    mysqldata: {}
    xhprof:

