version: '3.7'
services:
    web:
        image: nginx:latest
        ports:
            - "8082:8082"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:delegated
            - ./app:/app:delegated
        restart: always
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app:delegated
        restart: always
    cron:
        build:
            context: .
            dockerfile: CRON.Dockerfile
        restart: always
        volumes:
            - ./app:/app:delegated
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'purple'
            MYSQL_USER: 'moodleuser'
            MYSQL_PASSWORD: 'moodlepass'
            MYSQL_DATABASE: 'moodle44'
        restart: always
        volumes:
            - mysqldata:/var/lib/mysql:delegated
        ports:
            - 3308:3306
    redis:
        image: redis:latest
        restart: always
    maxima:
        image: unihalle/maximapool:latest
        restart: always
        environment:
            - MAXIMAPOOL_ADMIN_PASSWORD=purple
        ports:
            - "127.0.0.1:8765:8080"
        volumes:
            - "./maxima-pool.conf:/opt/maximapool/pool.conf:ro"
volumes:
    mysqldata: {}

